### PR TITLE
alert for more than one same ssids

### PR DESCRIPTION
**Pull request by omergunal**
if there are more than one same ssids in different addresses, print it

### CODE REVIEW

**Comment by cagataycali** [comment]
Did you try this proposal on your own local? Any proof of this concept for merge.

Another think is your commits, they should be rebased into one clear commit.

**Comment by omergunal** [comment]
@cagataycali yes i tried. https://ibb.co/gPAos6

**Comment by cagataycali** [comment]
IMHO commits should rebase into one commit and reasonable commit message.

Update pisavar.py does not make sense.

```
git rebase -i head~2 # like
```

**Comment by cagataycali** [comment]
More than this but it's ok for now. LGTM @besimaltnok

**Comment by besimaltnok** [comment]
Thanks for support Ömer, but this feature not for PiSavar. I will use this feature for PiDense module. maybe later I'll add this to PiSaVar but not now.

**Pull request closed without merging**
